---

- name:    Create Logstash directory /opt/apps/logstash/conf
  become:  true
  file:
    path:  /opt/apps/logstash/conf
    state: directory
    force: yes
  tags:
    - logstash

- name:    Copy Logstash config file
  become:  true
  copy:
    src:   logstash.conf
    dest:  /opt/apps/logstash/conf/logstash.conf
  tags:
    - logstash
